### ISSUE TITLE
fedimg fails on Modular compose

### ISSUE THREAD

**Issue by sayanchowdhury** [fedora-infra/fedimg#63]
```
Callstack that lead to the logging statement
--------------------------------------------
```python
  File "/usr/lib64/python2.7/threading.py", line 785 in __bootstrap
    self.__bootstrap_inner()
  File "/usr/lib64/python2.7/threading.py", line 812 in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 765 in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib64/python2.7/multiprocessing/pool.py", line 113 in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib64/python2.7/multiprocessing/pool.py", line 65 in mapstar
    return map(*args)
  File "/usr/lib/python2.7/site-packages/fedimg/uploader.py", line 47 in <lambda>
    results = pool.map(lambda s: s.upload(compose_meta), services)
  File "/usr/lib/python2.7/site-packages/fedimg/services/ec2.py", line 566 in upload
    log.exception("Failure")

Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/fedimg/services/ec2.py", line 313, in upload
    "output: {2}".format(status, cmd, data))
EC2UtilityException: Problem writing image to utility instance volume. Command exited with status 1.
command: sudo sh -c 'curl -L http://kojipkgs.fedoraproject.org/compose/Fedora-Modular-Rawhide-20170824.n.0/compose/CloudImages/x86_64/images/Fedora-Cloud-Base-Rawhide-20170824.n.0.x86_64.raw.xz | xzcat > /dev/xvdb'
output:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
114   458  114   458    0     0   1723      0 --:--:-- --:--:-- --:--:--  6361
  0   458    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
```

**Comment by sayanchowdhury** [comment]
This has been fixed in #90
